spring:
  datasource:
    url: jdbc:h2:mem:batchTest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform:  org.hibernate.dialect.H2Dialect

  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:sql/schema-h2.sql, classpath:sql/pay-mysql.sql

  # http://localhost:8080/h2-console
  # jdbc:h2:mem:batchTest
  h2:
    console:
      enabled: true
      path: /h2-console
