spring:
  application:
    name: kotlin-batch-practice

  profiles:
    active: local
    include: ${spring.profiles.active}

  batch:
    job:
      name: ${job.name:NONE}

    jdbc:
      initialize-schema: always
